name: Deployment pipeline

on:
  schedule: 
    - cron: '59 16 26 * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2
        # Check the following URLs one by one sequentially
        url: https://blooming-spire-39399.herokuapp.com/
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: false # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 2 # Optional, defaults to 1
        # Delay between retriespm
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false # Optional, defaults to "false"

